# Generated by Django 3.2.13 on 2023-03-29 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20230328_0346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='initiator',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='order',
            name='cell_phone',
        ),
    ]
