# Generated by Django 3.2.13 on 2023-03-29 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_basket_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='full_descriptions',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='products',
            name='manufacturer',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.CreateModel(
            name='ProductsGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products_images/gallery')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products')),
            ],
        ),
    ]
