# Generated by Django 3.2.13 on 2023-03-29 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20230329_0519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='full_descriptions',
            field=models.TextField(default=''),
        ),
    ]
